#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metanoia.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MetanoiaBD")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::Metanoia.Properties.Settings.Default.MetanoiaBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_MENSAJES_DIARIO")]
		public int SP_INSERTAR_MENSAJES_DIARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_TD_USUARIO_ID", DbType="Int")] System.Nullable<int> p_TD_USUARIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_TD_FECHA_CREADO", DbType="Date")] System.Nullable<System.DateTime> p_TD_FECHA_CREADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_TD_FECHA_ACTUALIZADO", DbType="Date")] System.Nullable<System.DateTime> p_TD_FECHA_ACTUALIZADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_TD_TITULO", DbType="VarChar(255)")] string p_TD_TITULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_TD_NOTA", DbType="VarChar(255)")] string p_TD_NOTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_TD_ESTADO", DbType="VarChar(25)")] string p_TD_ESTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_RETURN", DbType="Int")] ref System.Nullable<int> iD_RETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_DESCRIPCION", DbType="VarChar(255)")] ref string eRROR_DESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_TD_USUARIO_ID, p_TD_FECHA_CREADO, p_TD_FECHA_ACTUALIZADO, p_TD_TITULO, p_TD_NOTA, p_TD_ESTADO, iD_RETURN, eRROR_ID, eRROR_DESCRIPCION);
			iD_RETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRROR_DESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
