<?xml version="1.0" encoding="utf-8"?><Database Name="MetanoiaBD" Class="ConexionLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=metanoiaserv.database.windows.net;Initial Catalog=MetanoiaBD;User ID=Adminsql;Encrypt=True" SettingsObjectName="Metanoia.Properties.Settings" SettingsPropertyName="MetanoiaBDConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_INSERTAR_MENSAJES_DIARIO" Method="SP_INSERTAR_MENSAJES_DIARIO">
    <Parameter Name="P_TD_USUARIO_ID" Parameter="p_TD_USUARIO_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="P_TD_FECHA_CREADO" Parameter="p_TD_FECHA_CREADO" Type="System.DateTime" DbType="Date" />
    <Parameter Name="P_TD_FECHA_ACTUALIZADO" Parameter="p_TD_FECHA_ACTUALIZADO" Type="System.DateTime" DbType="Date" />
    <Parameter Name="P_TD_TITULO" Parameter="p_TD_TITULO" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="P_TD_NOTA" Parameter="p_TD_NOTA" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="P_TD_ESTADO" Parameter="p_TD_ESTADO" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="ID_RETURN" Parameter="iD_RETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERROR_ID" Parameter="eRROR_ID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERROR_DESCRIPCION" Parameter="eRROR_DESCRIPCION" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>