#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metanoia.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDMetanoia")]
	public partial class ConexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTabla_Chat_IA(Tabla_Chat_IA instance);
    partial void UpdateTabla_Chat_IA(Tabla_Chat_IA instance);
    partial void DeleteTabla_Chat_IA(Tabla_Chat_IA instance);
    partial void InsertTabla_Chat_Usuario(Tabla_Chat_Usuario instance);
    partial void UpdateTabla_Chat_Usuario(Tabla_Chat_Usuario instance);
    partial void DeleteTabla_Chat_Usuario(Tabla_Chat_Usuario instance);
    #endregion
		
		public ConexionLinqDataContext() : 
				base(global::Metanoia.Properties.Settings.Default.BDMetanoiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tabla_Chat_IA> Tabla_Chat_IA
		{
			get
			{
				return this.GetTable<Tabla_Chat_IA>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_Chat_Usuario> Tabla_Chat_Usuario
		{
			get
			{
				return this.GetTable<Tabla_Chat_Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Chat_IA")]
	public partial class Tabla_Chat_IA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Chat_IA_id;
		
		private int _Chat_IA_Sesion_id;
		
		private string _Chat_IA_Mensaje;
		
		private System.DateTime _Chat_IA_Mensaje_Fecha_hora;
		
		private string _Chat_IA_Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChat_IA_idChanging(int value);
    partial void OnChat_IA_idChanged();
    partial void OnChat_IA_Sesion_idChanging(int value);
    partial void OnChat_IA_Sesion_idChanged();
    partial void OnChat_IA_MensajeChanging(string value);
    partial void OnChat_IA_MensajeChanged();
    partial void OnChat_IA_Mensaje_Fecha_horaChanging(System.DateTime value);
    partial void OnChat_IA_Mensaje_Fecha_horaChanged();
    partial void OnChat_IA_EstadoChanging(string value);
    partial void OnChat_IA_EstadoChanged();
    #endregion
		
		public Tabla_Chat_IA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_IA_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Chat_IA_id
		{
			get
			{
				return this._Chat_IA_id;
			}
			set
			{
				if ((this._Chat_IA_id != value))
				{
					this.OnChat_IA_idChanging(value);
					this.SendPropertyChanging();
					this._Chat_IA_id = value;
					this.SendPropertyChanged("Chat_IA_id");
					this.OnChat_IA_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_IA_Sesion_id", DbType="Int NOT NULL")]
		public int Chat_IA_Sesion_id
		{
			get
			{
				return this._Chat_IA_Sesion_id;
			}
			set
			{
				if ((this._Chat_IA_Sesion_id != value))
				{
					this.OnChat_IA_Sesion_idChanging(value);
					this.SendPropertyChanging();
					this._Chat_IA_Sesion_id = value;
					this.SendPropertyChanged("Chat_IA_Sesion_id");
					this.OnChat_IA_Sesion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_IA_Mensaje", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Chat_IA_Mensaje
		{
			get
			{
				return this._Chat_IA_Mensaje;
			}
			set
			{
				if ((this._Chat_IA_Mensaje != value))
				{
					this.OnChat_IA_MensajeChanging(value);
					this.SendPropertyChanging();
					this._Chat_IA_Mensaje = value;
					this.SendPropertyChanged("Chat_IA_Mensaje");
					this.OnChat_IA_MensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_IA_Mensaje_Fecha_hora", DbType="DateTime NOT NULL")]
		public System.DateTime Chat_IA_Mensaje_Fecha_hora
		{
			get
			{
				return this._Chat_IA_Mensaje_Fecha_hora;
			}
			set
			{
				if ((this._Chat_IA_Mensaje_Fecha_hora != value))
				{
					this.OnChat_IA_Mensaje_Fecha_horaChanging(value);
					this.SendPropertyChanging();
					this._Chat_IA_Mensaje_Fecha_hora = value;
					this.SendPropertyChanged("Chat_IA_Mensaje_Fecha_hora");
					this.OnChat_IA_Mensaje_Fecha_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_IA_Estado", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Chat_IA_Estado
		{
			get
			{
				return this._Chat_IA_Estado;
			}
			set
			{
				if ((this._Chat_IA_Estado != value))
				{
					this.OnChat_IA_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Chat_IA_Estado = value;
					this.SendPropertyChanged("Chat_IA_Estado");
					this.OnChat_IA_EstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Chat_Usuario")]
	public partial class Tabla_Chat_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Chat_Usuario_id;
		
		private int _Chat_Usuario_Sesion_id;
		
		private string _Chat_Usuario_Mensaje;
		
		private System.DateTime _Chat_Usuario_Mensaje_Fecha_hora;
		
		private string _Chat_IA_Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChat_Usuario_idChanging(int value);
    partial void OnChat_Usuario_idChanged();
    partial void OnChat_Usuario_Sesion_idChanging(int value);
    partial void OnChat_Usuario_Sesion_idChanged();
    partial void OnChat_Usuario_MensajeChanging(string value);
    partial void OnChat_Usuario_MensajeChanged();
    partial void OnChat_Usuario_Mensaje_Fecha_horaChanging(System.DateTime value);
    partial void OnChat_Usuario_Mensaje_Fecha_horaChanged();
    partial void OnChat_IA_EstadoChanging(string value);
    partial void OnChat_IA_EstadoChanged();
    #endregion
		
		public Tabla_Chat_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_Usuario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Chat_Usuario_id
		{
			get
			{
				return this._Chat_Usuario_id;
			}
			set
			{
				if ((this._Chat_Usuario_id != value))
				{
					this.OnChat_Usuario_idChanging(value);
					this.SendPropertyChanging();
					this._Chat_Usuario_id = value;
					this.SendPropertyChanged("Chat_Usuario_id");
					this.OnChat_Usuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_Usuario_Sesion_id", DbType="Int NOT NULL")]
		public int Chat_Usuario_Sesion_id
		{
			get
			{
				return this._Chat_Usuario_Sesion_id;
			}
			set
			{
				if ((this._Chat_Usuario_Sesion_id != value))
				{
					this.OnChat_Usuario_Sesion_idChanging(value);
					this.SendPropertyChanging();
					this._Chat_Usuario_Sesion_id = value;
					this.SendPropertyChanged("Chat_Usuario_Sesion_id");
					this.OnChat_Usuario_Sesion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_Usuario_Mensaje", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Chat_Usuario_Mensaje
		{
			get
			{
				return this._Chat_Usuario_Mensaje;
			}
			set
			{
				if ((this._Chat_Usuario_Mensaje != value))
				{
					this.OnChat_Usuario_MensajeChanging(value);
					this.SendPropertyChanging();
					this._Chat_Usuario_Mensaje = value;
					this.SendPropertyChanged("Chat_Usuario_Mensaje");
					this.OnChat_Usuario_MensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_Usuario_Mensaje_Fecha_hora", DbType="DateTime NOT NULL")]
		public System.DateTime Chat_Usuario_Mensaje_Fecha_hora
		{
			get
			{
				return this._Chat_Usuario_Mensaje_Fecha_hora;
			}
			set
			{
				if ((this._Chat_Usuario_Mensaje_Fecha_hora != value))
				{
					this.OnChat_Usuario_Mensaje_Fecha_horaChanging(value);
					this.SendPropertyChanging();
					this._Chat_Usuario_Mensaje_Fecha_hora = value;
					this.SendPropertyChanged("Chat_Usuario_Mensaje_Fecha_hora");
					this.OnChat_Usuario_Mensaje_Fecha_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chat_IA_Estado", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Chat_IA_Estado
		{
			get
			{
				return this._Chat_IA_Estado;
			}
			set
			{
				if ((this._Chat_IA_Estado != value))
				{
					this.OnChat_IA_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Chat_IA_Estado = value;
					this.SendPropertyChanged("Chat_IA_Estado");
					this.OnChat_IA_EstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
